### ISSUE TITLE
NoClassDefFoundError: groovyx/gpars/util/PoolFactory after upgrading from version 2.0.10 to 3.1.2

### ISSUE THREAD

**Issue by LuisMuniz** [budjb/grails-rabbitmq-native#72]
Hi,

Great plugin, I have been using an older version in almost all my projects. However now I would like to use the ability to start and stop consumers, so I am upgrading.

I am running my unit test on a clean build container on shippable, so there is no issue of old classes hanging around.

When I run my unit tests, I get the following stack trace:

``` groovy
|  java.lang.NoClassDefFoundError: groovyx/gpars/util/PoolFactory
        at grails.async.Promises.<clinit>(Promises.java:40)
        at grails.test.runtime.GrailsApplicationTestPlugin.initialState(GrailsApplicationTestPlugin.groovy:178)
        at grails.test.runtime.GrailsApplicationTestPlugin.onTestEvent(GrailsApplicationTestPlugin.groovy:326)
        at grails.test.runtime.TestRuntime.deliverEvent(TestRuntime.groovy:295)
        at grails.test.runtime.TestRuntime.executeEventLoop(TestRuntime.groovy:280)
        at grails.test.runtime.TestRuntime.processEvents(TestRuntime.groovy:265)
        at grails.test.runtime.TestRuntime.doPublishEvent(TestRuntime.groovy:238)
        at grails.test.runtime.TestRuntime.publishEvent(TestRuntime.groovy:211)
        at grails.test.runtime.TestRuntime.getValue(TestRuntime.groovy:122)
        at grails.test.runtime.GrailsApplicationTestPlugin.onTestEvent(GrailsApplicationTestPlugin.groovy:320)
        at grails.test.runtime.TestRuntime.deliverEvent(TestRuntime.groovy:295)
        at grails.test.runtime.TestRuntime.processEvents(TestRuntime.groovy:264)
        at grails.test.runtime.TestRuntime.doPublishEvent(TestRuntime.groovy:248)
        at grails.test.runtime.TestRuntime.publishEvent(TestRuntime.groovy:211)
        at grails.test.runtime.TestRuntimeJunitAdapter.before(TestRuntimeJunitAdapter.groovy:109)
        at grails.test.runtime.TestRuntimeJunitAdapter$1$2.evaluate(TestRuntimeJunitAdapter.groovy:47)
        at org.spockframework.runtime.extension.builtin.TestRuleInterceptor.intercept(TestRuleInterceptor.java:38)
        at org.spockframework.runtime.extension.MethodInvocation.proceed(MethodInvocation.java:87)
        at org.spockframework.runtime.extension.MethodInvocation.proceed(MethodInvocation.java:88)
        at org.spockframework.runtime.extension.builtin.AbstractRuleInterceptor$1.evaluate(AbstractRuleInterceptor.java:37)
        at grails.test.runtime.TestRuntimeJunitAdapter$3$4.evaluate(TestRuntimeJunitAdapter.groovy:76)
        at org.spockframework.runtime.extension.builtin.ClassRuleInterceptor.intercept(ClassRuleInterceptor.java:38)
        at org.spockframework.runtime.extension.MethodInvocation.proceed(MethodInvocation.java:87)
Caused by: java.lang.ClassNotFoundException: groovyx.gpars.util.PoolFactory
        at org.codehaus.groovy.tools.RootLoader.findClass(RootLoader.java:179)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at org.codehaus.groovy.tools.RootLoader.loadClass(RootLoader.java:151)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        ... 23 more
|
```

I see that you include the (very old, and seemingly unsupported) gpars plugin in your dependencies. Could this be related, and Is this still needed? Grails seems to be shipping with their own gpars implementation.

**Comment by LuisMuniz** [comment]
Additional information. I'm using grails 2.5.1

**Comment by LuisMuniz** [comment]
Confirmed, that when I install your plugin in the following way:

``` groovy
        compile (":rabbitmq-native:3.1.2") {
            excludes ("gpars")
        }
```

The tests pass

**Comment by budjb** [comment]
Did you enable legacyResolve in the build config?

I'd be happy to look at a built-in Grails gpars library if you can point me to some docs that explain its usage.

**Comment by LuisMuniz** [comment]
legacyResolve is off

When I look for GparsPool in my IDE (intellij) I can find it in the grails-2.5.1 library. 

From the grails dependency report:

```
+--- org.grails:grails-plugin-async:2.5.1
|    \--- org.grails:grails-async:2.5.1
|         \--- org.codehaus.gpars:gpars:1.2.1
```

Does this help?

**Comment by budjb** [comment]
It does, I'll work on getting this removed.

**Comment by LuisMuniz** [comment]
Thanks!

**Comment by budjb** [comment]
This will be available in 3.1.3.

**Comment by LuisMuniz** [comment]
thanks
